// The ONE canonical answer to "daily summary" / "what are we looking at today?".
// Built only from database records with a fixed template, so the dashboard, Grokbot and Claude
// all give the same answer. Nothing here is generated by a model at request time.
// Same layout every day, built to be skimmed in the morning (Stavros, 2026-10-08).

import { getSystemState, getYesterdayReview } from "./db";
import { fmtPct, fmtRR, getLeverageDesk, getRobinhoodBook, isDeskAlert, tradeMetrics } from "./desk";

const n = (v: unknown, d = 2) =>
  v === null || v === undefined || v === "" || Number.isNaN(Number(v))
    ? "—"
    : Number(v).toLocaleString("en-US", { maximumFractionDigits: d });
const usd = (v: unknown) =>
  v === null || v === undefined || Number.isNaN(Number(v))
    ? "—"
    : `${Number(v) < 0 ? "-" : ""}$${Math.abs(Number(v)).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const phx = (iso?: string | null) =>
  iso
    ? new Date(iso).toLocaleString("en-US", { timeZone: "America/Phoenix", weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })
    : "—";

type Tier = { below?: number; grade5?: number; grade4?: number };

/** Risk percent for grade 5 / grade 4 at the current account size. */
function riskNow(equity: number, rules: Record<string, unknown> | undefined, fallback: number) {
  const tiers = Array.isArray(rules?.risk_tiers) ? (rules!.risk_tiers as Tier[]) : [];
  const t = tiers.find((x) => x.below == null || equity < Number(x.below));
  return { g5: Number(t?.grade5 ?? fallback), g4: Number(t?.grade4 ?? fallback / 2) };
}

const firstSentence = (t?: string | null, max = 180) => {
  if (!t) return "";
  const m = t.match(/^.*?[.!?](\s|$)/);
  const x = (m ? m[0] : t).trim();
  return x.length > max ? `${x.slice(0, max - 1)}…` : x;
};

export type BriefCoin = {
  asset: string;
  price: number | null;
  change24: number | null;
  bias: string;
  htf: string | null;
  regime: string | null;
  above: number[];
  below: number[];
  /** The two lines on the TradingView chart (Cartographer): range high and range low. */
  rangeHigh: number | null;
  rangeLow: number | null;
  /** Short form of the plays for the X post, e.g. "short <80,345 hold · short reject 83,500". */
  playLine: string | null;
  plan: string;
  deskAlert: boolean;
  checkedAt: string | null;
};

export async function buildBriefing() {
  const [state, lev, rh, yesterday] = await Promise.all([getSystemState(), getLeverageDesk(), getRobinhoodBook(), getYesterdayReview()]);
  const now = new Date().toISOString();
  const risk = riskNow(lev.equity, lev.strategy?.rules, Number(lev.risk?.risk_per_trade_pct ?? 2));

  // ------------------------------------------------------------ structured brief (the dashboard draws this)
  const live = lev.signals.filter((s) => ["armed", "triggered"].includes(s.status) && !s.outcome && isDeskAlert(s));
  const research = lev.signals.filter((s) => ["watching", "armed", "triggered"].includes(s.status) && !s.outcome && !isDeskAlert(s));
  const coins: BriefCoin[] = ["BTC", "ETH"].map((a) => {
    const h = lev.latest[a];
    const t = lev.theses.find((x) => x.asset === a);
    const lv = (h?.levels ?? t?.levels ?? {}) as { support?: number[]; resistance?: number[]; range_high?: number; range_low?: number };
    const price = h ? Number(h.price) : null;
    const above = (lv.resistance ?? []).map(Number).filter((x) => price == null || x > price).sort((x, y) => x - y).slice(0, 2);
    const below = (lv.support ?? []).map(Number).filter((x) => price == null || x < price).sort((x, y) => y - x).slice(0, 2);
    const sig = live.find((s) => s.asset === a);
    const open = lev.openTrades.find((tr) => tr.symbol === a);
    const rh = lv.range_high != null && (price == null || Number(lv.range_high) > price) ? Number(lv.range_high) : null;
    const rl = lv.range_low != null && (price == null || Number(lv.range_low) < price) ? Number(lv.range_low) : null;
    const coinPlays = lev.signals
      .filter((s) => s.asset === a && ["watching", "armed"].includes(s.status) && !s.outcome)
      .sort((x, y) => Number(y.trigger_price ?? y.entry) - Number(x.trigger_price ?? x.entry));
    const playLine = coinPlays.length
      ? coinPlays.map((s) => `${s.direction} ${price != null && Number(s.trigger_price ?? s.entry) < price ? "below" : "above"} ${n(s.trigger_price ?? s.entry, 0)}`).join(" · ")
      : null;
    let plan: string;
    if (open) {
      const m = tradeMetrics(open);
      plan = `IN A TRADE: ${open.direction} @ ${n(open.entry)} · stop ${n(open.current_stop ?? open.stop)} · TP1 ${n(open.current_tp1 ?? open.tp1 ?? open.target)} · R:R ${fmtRR(m.rr)}`;
    } else if (sig) {
      plan = `DESK ALERT: ${sig.direction.toUpperCase()} · grade ${sig.confidence_grade} (${n(sig.confidence_score, 0)}/100) · ${sig.trigger_condition ?? `trigger ${n(sig.trigger_price)}`} · entry ${n(sig.entry)} stop ${n(sig.stop)} TP1 ${n(sig.tp1)} · R:R ${fmtRR(sig.rr_tp1)} · account ${fmtPct(-Number(sig.risk_percent ?? 0))} / ${fmtPct(Number(sig.risk_percent ?? 0) * Number(sig.rr_tp1 ?? 0))}`;
    } else {
      // Level plays: the two conditional trades sitting in TradingView for this coin (above and below price).
      const plays = lev.signals
        .filter((s) => s.asset === a && ["watching", "armed"].includes(s.status) && !s.outcome)
        .sort((x, y) => Number(y.trigger_price ?? y.entry) - Number(x.trigger_price ?? x.entry));
      plan = plays.length
        ? `PLAYS: ${plays
            .map((s) => {
              const lvl = Number(s.trigger_price ?? s.entry);
              const side = price != null && lvl < price ? "▼" : "▲";
              return `${side} ${n(lvl)} ${s.direction.toUpperCase()} (${n(s.confidence_score, 0)}, R:R ${fmtRR(s.rr_tp1)}) if ${s.trigger_condition ?? "validated"}`;
            })
            .join("  ·  ")}`
        : `No plays set yet — key levels ${above[0] ? n(above[0]) : "—"} / ${below[0] ? n(below[0]) : "—"}`;
    }
    const ch = h?.indicators && (h.indicators as Record<string, unknown>).change_24h_pct;
    return {
      asset: a,
      price,
      change24: ch == null || Number.isNaN(Number(ch)) ? null : Number(ch),
      bias: h?.bias ?? t?.bias ?? "—",
      htf: h?.htf_bias ?? null,
      regime: h?.regime ?? null,
      above,
      below,
      rangeHigh: rh,
      rangeLow: rl,
      playLine,
      plan,
      deskAlert: !!sig,
      checkedAt: h?.ts ?? null,
    };
  });

  // Rotation: the Scout's top 5 vs BTC and the (max 2) coins in play, with their level plays.
  const rotationCoins = lev.universe.filter((u) => u.tier === "rotation").sort((x, y) => Number(x.rank ?? 99) - Number(y.rank ?? 99));
  const rotation = {
    top: rotationCoins.slice(0, 5).map((u) => ({ asset: u.asset, rank: u.rank, rs1m: u.rs_1m_vs_btc == null ? null : Number(u.rs_1m_vs_btc), inPlay: u.in_play })),
    plays: rotationCoins
      .filter((u) => u.in_play)
      .map((u) => ({
        asset: u.asset,
        plays: lev.signals
          .filter((s) => s.asset === u.asset && ["watching", "armed"].includes(s.status) && !s.outcome)
          .map((s) => `${s.direction.toUpperCase()} ${n(s.trigger_price ?? s.entry)} (${n(s.confidence_score, 0)}, R:R ${fmtRR(s.rr_tp1)})`),
      })),
  };

  const tickers = rh.tickerTheses.filter((t) => t.setup_score != null).sort((x, y) => Number(y.setup_score) - Number(x.setup_score));
  const best = tickers[0] ?? null;
  const grade = (sc: number) => (sc >= 8 ? "A" : sc >= 6.5 ? "B" : "C");
  const scores = yesterday.evaluations.map((e) => Number(e.total_score)).filter((x) => !Number.isNaN(x));
  const lessonRow = [...lev.journal, ...rh.journal].sort((x, y) => y.created_at.localeCompare(x.created_at))[0];
  const lesson = lessonRow?.rule_change || yesterday.evaluations.find((e) => e.lesson)?.lesson || null;

  const brief = {
    date: now,
    market: {
      regime: state?.current_regime ?? rh.master?.market_regime ?? null,
      risk: state?.risk_environment ?? rh.master?.risk_environment ?? null,
      bias: rh.master?.bias ?? null,
      confidence: state?.system_confidence ?? null,
      view: firstSentence(rh.master?.primary_scenario),
      changeMind: firstSentence(rh.master?.what_changes_our_mind, 140),
    },
    coins,
    rotation,
    stocks: {
      bias: rh.equityThesis?.bias ?? null,
      view: firstSentence(rh.equityThesis?.primary_scenario),
      best: best ? { symbol: best.asset, score: Number(best.setup_score), grade: grade(Number(best.setup_score)) } : null,
    },
    today: (rh.master?.catalysts ?? []).slice(0, 4).map((c) => firstSentence(String(c), 90)),
    books: {
      leverage: { equity: lev.equity, milestone: lev.milestone, open: lev.openTrades.length, riskG5: risk.g5, riskG4: risk.g4 },
      robinhood: {
        equity: rh.snapshot?.equity ?? null,
        positions: rh.open.map((t) => t.symbol),
        boxUsed: rh.box.used,
        boxLimit: rh.box.limit,
        fills: rh.fillsThisWeek,
        maxFills: rh.risk?.max_fills_per_week ?? 2,
      },
    },
    yesterday: { graded: scores.length, avg: scores.length ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length) : null, lesson },
  };

  // ------------------------------------------------------------ text — same layout every day
  const arrow = (b?: string | null) => (b === "bullish" ? "▲" : b === "bearish" ? "▼" : "◆");
  const L: string[] = [];
  L.push(`MOONBAG MORNING BRIEF · ${phx(now)}`);
  L.push("");
  L.push(`THE MARKET  ${brief.market.risk ?? "—"} · ${(brief.market.bias ?? "—").toUpperCase()} · confidence ${n(brief.market.confidence ?? 0, 0)}/100`);
  if (brief.market.view) L.push(`  ${brief.market.view}`);
  if (brief.market.changeMind) L.push(`  Changes our mind: ${brief.market.changeMind}`);
  L.push("");
  for (const c of coins) {
    L.push(`${c.asset}  ${n(c.price)}  ${arrow(c.bias)} ${c.change24 == null ? "" : `${fmtPct(c.change24)} 24h  `}${c.bias.toUpperCase()}${c.htf ? ` (4h ${c.htf}${c.regime ? ` · ${c.regime}` : ""})` : ""}`);
    L.push(`  Range lines ${c.rangeLow != null ? n(c.rangeLow) : "—"} / ${c.rangeHigh != null ? n(c.rangeHigh) : "—"} · Above: ${c.above.length ? c.above.map((x) => n(x)).join(" · ") : "—"} · Below: ${c.below.length ? c.below.map((x) => n(x)).join(" · ") : "—"}`);
    L.push(`  ▸ ${c.plan}`);
  }
  L.push("");
  L.push(`ROTATION  ${rotation.top.length ? rotation.top.map((r) => `${r.asset} ${r.rs1m == null ? "" : `${r.rs1m > 0 ? "+" : ""}${n(r.rs1m, 0)}%`}${r.inPlay ? "★" : ""}`).join(" · ") : "Not ranked yet"}  (1M vs BTC · ★ in play)`);
  for (const r of rotation.plays) L.push(`  ▸ ${r.asset}: ${r.plays.length ? r.plays.join("  ·  ") : "no plays set yet"}`);
  L.push("");
  L.push(`STOCKS  ${(brief.stocks.bias ?? "—").toUpperCase()}${brief.stocks.view ? ` — ${brief.stocks.view}` : ""}`);
  L.push(`  ▸ ${brief.stocks.best ? `Best setup: ${brief.stocks.best.symbol} ${n(brief.stocks.best.score, 1)}/10 (${brief.stocks.best.grade})` : "No equity setup scored yet"}`);
  L.push("");
  L.push(`TODAY  ${brief.today.length ? brief.today.join(" · ") : "No major events recorded"}`);
  L.push("");
  L.push("YOUR BOOKS");
  L.push(`  Leverage   ${usd(lev.equity)}${lev.milestone ? ` → next ${usd(lev.milestone)}` : ""} · ${lev.openTrades.length ? `${lev.openTrades.length} open trade` : "no open trade"} · risk ${n(risk.g5, 1)}% A+ / ${n(risk.g4, 1)}% A`);
  L.push(`  Robinhood  ${rh.snapshot ? usd(rh.snapshot.equity) : "—"} · ${rh.open.length ? rh.open.map((t) => t.symbol).join(", ") : "cash"} · loss box ${usd(rh.box.used)}/${usd(rh.box.limit)} · fills ${rh.fillsThisWeek}/${n(rh.risk?.max_fills_per_week ?? 2, 0)}`);
  L.push("");
  L.push(`YESTERDAY  ${brief.yesterday.avg != null ? `forecasts graded ${brief.yesterday.avg}/100 avg (${brief.yesterday.graded})` : "not graded yet"}`);
  if (lesson) L.push(`  Lesson: ${firstSentence(lesson, 200)}`);
  L.push("");
  L.push("Source: Moonbag database. Not financial advice. Stavros places every BloFin order.");

  return {
    generated_at: now,
    text: L.join("\n"),
    brief,
    data: {
      system_state: state,
      leverage: {
        equity: lev.equity,
        next_milestone: lev.milestone,
        strategy_version: lev.strategy?.version ?? null,
        risk_percent: risk,
        latest: lev.latest,
        signals: [...live, ...research],
        open_trades: lev.openTrades,
        alerts: lev.alerts.filter((a) => a.status === "active"),
      },
      robinhood: {
        equity: rh.snapshot?.equity ?? null,
        loss_box: rh.box,
        fills_this_week: rh.fillsThisWeek,
        open_trades: rh.open,
        pending_handoffs: rh.handoffs.filter((h) => ["pending", "acknowledged"].includes(h.status)),
      },
    },
  };
}
