// The ONE canonical answer to "daily summary" / "what are we looking at today?".
// Built only from database records with a fixed template, so the dashboard, Grokbot and Claude
// all give the same answer. Nothing here is generated by a model at request time.

import { getSystemState } from "./db";
import { fmtPct, fmtRR, getLeverageDesk, getRobinhoodBook, isDeskAlert, tradeMetrics } from "./desk";

const n = (v: unknown, d = 2) =>
  v === null || v === undefined || v === "" || Number.isNaN(Number(v))
    ? "—"
    : Number(v).toLocaleString("en-US", { maximumFractionDigits: d });
const usd = (v: unknown) =>
  v === null || v === undefined || Number.isNaN(Number(v))
    ? "—"
    : `${Number(v) < 0 ? "-" : ""}$${Math.abs(Number(v)).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const lvl = (v: unknown) => (Array.isArray(v) && v.length ? v.map((x) => n(x)).join(", ") : "—");
const phx = (iso?: string | null) =>
  iso
    ? new Date(iso).toLocaleString("en-US", { timeZone: "America/Phoenix", weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })
    : "—";

type Tier = { below?: number; grade5?: number; grade4?: number };

/** Risk percent for grade 5 / grade 4 at the current account size. */
function riskNow(equity: number, rules: Record<string, unknown> | undefined, fallback: number) {
  const tiers = Array.isArray(rules?.risk_tiers) ? (rules!.risk_tiers as Tier[]) : [];
  const t = tiers.find((x) => x.below == null || equity < Number(x.below));
  return { g5: Number(t?.grade5 ?? fallback), g4: Number(t?.grade4 ?? fallback / 2) };
}

export async function buildBriefing() {
  const [state, lev, rh] = await Promise.all([getSystemState(), getLeverageDesk(), getRobinhoodBook()]);
  const now = new Date().toISOString();
  const L: string[] = [];

  // ------------------------------------------------------------ header
  L.push(`MOONBAG BRIEFING — ${phx(now)} (Phoenix)`);
  L.push(
    `System confidence ${n(state?.system_confidence ?? 0, 0)}/100 (${state?.forecasts_graded ?? 0} graded) · Regime: ${state?.current_regime ?? rh.master?.market_regime ?? "—"} · Risk: ${state?.risk_environment ?? rh.master?.risk_environment ?? "—"}`
  );

  // ------------------------------------------------------------ market view
  L.push("");
  L.push("MARKET VIEW");
  if (rh.master) {
    L.push(`${rh.master.bias.toUpperCase()} — ${rh.master.primary_scenario ?? "no scenario written"}`);
    if (rh.master.what_changes_our_mind) L.push(`What changes our mind: ${rh.master.what_changes_our_mind}`);
  } else {
    L.push("No master thesis is active.");
  }

  // ------------------------------------------------------------ book 2: leverage
  const risk = riskNow(lev.equity, lev.strategy?.rules, Number(lev.risk?.risk_per_trade_pct ?? 2));
  L.push("");
  L.push(
    `LEVERAGE DESK (BloFin) — ${usd(lev.equity)}${lev.milestone ? ` → next ${usd(lev.milestone)}` : ""} · strategy v${lev.strategy?.version ?? "—"} · risk ${n(risk.g5, 1)}% on grade 5, ${n(risk.g4, 1)}% on grade 4`
  );
  for (const a of ["BTC", "ETH"]) {
    const h = lev.latest[a];
    const t = lev.theses.find((x) => x.asset === a);
    if (!h && !t) {
      L.push(`${a}: no data yet.`);
      continue;
    }
    const lv = (h?.levels ?? t?.levels ?? {}) as { support?: number[]; resistance?: number[]; breakout?: number | null; invalidation?: number | null };
    L.push(`${a} ${h ? n(h.price) : "—"} · ${h?.bias ?? t?.bias ?? "—"}${h?.htf_bias ? ` (higher timeframe ${h.htf_bias})` : ""}${h?.regime ? ` · ${h.regime}` : ""}`);
    L.push(`  Resistance ${lvl(lv.resistance)} · Support ${lvl(lv.support)} · Breakout ${n(lv.breakout)} · Invalidation ${n(lv.invalidation)}`);
    if (h?.note) L.push(`  ${h.note}`);
  }

  const live = lev.signals.filter((s) => ["armed", "triggered"].includes(s.status) && !s.outcome && isDeskAlert(s));
  const watching = lev.signals.filter((s) => ["watching", "armed", "triggered"].includes(s.status) && !s.outcome && !isDeskAlert(s));
  if (live.length) {
    for (const s of live) {
      L.push(
        `DESK ALERT — ${s.asset} ${s.direction.toUpperCase()} · grade ${s.confidence_grade} (${n(s.confidence_score, 0)}/100) · ${s.setup_id} · ${s.status.toUpperCase()}`
      );
      if (s.trigger_condition) L.push(`  Trigger: ${s.trigger_condition}`);
      L.push(
        `  Entry ${n(s.entry)} · Stop ${n(s.stop)} · TP1 ${n(s.tp1)} (${n(s.rr_tp1, 1)}R) · Size ${n(s.quantity, 4)} (${usd(s.notional)}) · Lev ${n(s.leverage, 0)}x · Margin ${usd(s.margin)} · Risk ${usd(s.risk_dollars)}`
      );
      L.push(
        `  R:R ${fmtRR(s.rr_tp1)} · Account ${fmtPct(-Number(s.risk_percent ?? 0))} at the stop / ${fmtPct(Number(s.risk_percent ?? 0) * Number(s.rr_tp1 ?? 0))} at TP1`
      );
      if (s.evidence_against) L.push(`  Wrong if: ${s.evidence_against}`);
    }
  } else {
    L.push("Setups: no DESK ALERT. Waiting for price to reach a level.");
  }
  if (watching.length) {
    L.push(`RESEARCH ONLY (paper-tracked): ${watching.map((s) => `${s.asset} ${s.direction} ${s.setup_id} ${n(s.confidence_score, 0)}/100`).join(" · ")}`);
  }
  L.push(
    lev.openTrades.length
      ? `Open trade: ${lev.openTrades.map((t) => { const m = tradeMetrics(t); return `${t.symbol} ${t.direction} @ ${n(t.entry)} · stop ${n(t.current_stop ?? t.stop)} · TP1 ${n(t.current_tp1 ?? t.tp1 ?? t.target)} · R:R ${fmtRR(m.rr)} · account ${fmtPct(m.riskPct)} at the stop / ${fmtPct(m.rewardPct)} at TP1`; }).join(" | ")}`
      : "Open trade: none."
  );
  const live_alerts = lev.alerts.filter((a) => a.status === "active");
  L.push(
    `TradingView alerts live: ${
      live_alerts.length
        ? live_alerts
            .map((a) => `${a.asset} ${a.condition === "cross_up" ? "↑" : "↓"} ${n(a.trigger_price)} (${a.action === "ENTER" ? `${a.direction} trigger` : a.action === "EXIT" ? "trade level" : "level watch"})`)
            .join(" · ")
        : "none"
    }`
  );
  L.push(`Last hourly check: ${lev.hourly[0] ? phx(lev.hourly[0].ts) : "none yet"}`);

  // ------------------------------------------------------------ book 1: robinhood
  L.push("");
  L.push(
    `LONG-TERM BOOK (Robinhood) — ${rh.snapshot ? usd(rh.snapshot.equity) : "no account snapshot"} · loss box ${usd(rh.box.used)} of ${usd(rh.box.limit)} · fills ${rh.fillsThisWeek}/${n(rh.risk?.max_fills_per_week, 0)} this week`
  );
  if (rh.equityThesis) L.push(`Equities: ${rh.equityThesis.bias.toUpperCase()} — ${rh.equityThesis.primary_scenario ?? "no scenario written"}`);
  L.push(
    rh.open.length
      ? `Positions: ${rh.open.map((t) => `${t.symbol} ${n(t.quantity, 4)} @ ${n(t.entry)} · stop ${n(t.current_stop ?? t.stop)} · target ${n(t.current_tp1 ?? t.tp1 ?? t.target)}`).join(" | ")}`
      : "Positions: in cash — no A-grade setup has met the standard."
  );
  const pending = rh.handoffs.filter((h) => ["pending", "acknowledged"].includes(h.status));
  L.push(
    `Handoffs waiting: ${pending.length ? pending.map((h) => `${h.symbol} (${h.status})`).join(", ") : "none"} · Paper trades open: ${rh.paper.filter((p) => p.status === "open").length} · Active themes: ${rh.themes.filter((t) => t.status === "active").length}`
  );

  // ------------------------------------------------------------ footer
  const lesson = lev.journal[0] ?? rh.journal[0];
  if (lesson?.rule_change) {
    L.push("");
    L.push(`Latest rule change: ${lesson.rule_change}`);
  }
  L.push("");
  L.push("Source: Moonbag database. Not financial advice. Stavros places every BloFin order.");

  return {
    generated_at: now,
    text: L.join("\n"),
    data: {
      system_state: state,
      leverage: {
        equity: lev.equity,
        next_milestone: lev.milestone,
        strategy_version: lev.strategy?.version ?? null,
        risk_percent: risk,
        latest: lev.latest,
        signals: [...live, ...watching],
        open_trades: lev.openTrades,
        alerts: live_alerts,
      },
      robinhood: {
        equity: rh.snapshot?.equity ?? null,
        loss_box: rh.box,
        fills_this_week: rh.fillsThisWeek,
        open_trades: rh.open,
        pending_handoffs: pending,
      },
    },
  };
}
